# libnixexpr, transcribed from src/libexpr/meson.build and its subdirectories.
{
  pkgs,
  nixMake,
  nix-util,
  nix-store,
  nix-fetchers,
}:

let
  # The parser and lexer are generated by bison and flex. The scanner is
  # told (via `generated`) that their outputs inherit the #includes of
  # parser.y and lexer.l, so it does not need to build them at evaluation
  # time.
  parserTab = pkgs.runCommand "parser-tab" { nativeBuildInputs = [ pkgs.bison ]; } ''
    mkdir $out
    bison -v -o $out/parser-tab.cc -d ${../../src/libexpr/parser.y}
  '';

  lexerTab = pkgs.runCommand "lexer-tab" { nativeBuildInputs = [ pkgs.flex ]; } ''
    mkdir $out
    flex -Cf --outfile $out/lexer-tab.cc --header-file=$out/lexer-tab.hh ${../../src/libexpr/lexer.l}
  '';
in

nixMake.mkComponent {
  name = "nix-expr";
  libName = "nixexpr";

  deps = [
    nix-util
    nix-store
    nix-fetchers
  ];

  root = ../../src/libexpr;

  includeDirs = [
    ""
    "include"
  ];

  files = nixMake.commonSupportFiles // {
    "imported-drv-to-derivation.nix.gen.hh" =
      nixMake.mkStringHeader ../../src/libexpr/imported-drv-to-derivation.nix;
    "fetchurl.nix.gen.hh" = nixMake.mkStringHeader ../../src/libexpr/fetchurl.nix;
    "primops/derivation.nix.gen.hh" = nixMake.mkStringHeader ../../src/libexpr/primops/derivation.nix;
  };

  generated = {
    "parser-tab.hh" = {
      from = "parser.y";
      path = "${parserTab}/parser-tab.hh";
    };
    "parser-tab.cc" = {
      from = "parser.y";
      path = "${parserTab}/parser-tab.cc";
    };
    "lexer-tab.hh" = {
      from = "lexer.l";
      path = "${lexerTab}/lexer-tab.hh";
    };
    "lexer-tab.cc" = {
      from = "lexer.l";
      path = "${lexerTab}/lexer-tab.cc";
    };
  };

  configHeaders = {
    "include/nix/expr/config.hh" = {
      NIX_USE_BOEHMGC = 1;
    };
    "expr-config-private.hh" = {
      HAVE_PTHREAD_GETATTR_NP = 1;
      HAVE_SYSCONF = 1;
      HAVE_TOML11_4 = 1;
    };
  };

  linkFlags = [ "-Wl,--wrap=__assert_fail" ];
}
