on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      system:
        required: true
        type: string
      if:
        required: false
        default: true
        type: boolean
      run_tests:
        required: false
        default: true
        type: boolean

jobs:
  build:
    if: ${{ inputs.if }}
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build .#packages.${{ inputs.system }}.default .#packages.${{ inputs.system }}.binaryTarball --no-link -L
      - run: nix build .#packages.${{ inputs.system }}.binaryTarball --out-link tarball
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.system }}
          path: ./tarball/*.xz
  test:
    if: ${{ inputs.if && inputs.run_tests}}
    needs: build
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake check -L --system ${{ inputs.system }}
