name: Mirror to FlakeHub

on:
  push:
  #pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: v3.21.1

      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v3

      - name: Build
        id: build
        run: |
          nix build ./packaging/secure-packages#fallbackPathsNix
          echo "store-path=$(readlink -f result)" >> "$GITHUB_OUTPUT"

      # Pass one path, or several newline-separated paths.
      - uses: DeterminateSystems/public-slice-mirror/.github/actions/upload-store-paths@main
        with:
          store-paths: ${{ steps.build.outputs.store-path }}
          # name: store-paths   # optional, this is the default artifact name

  mirror:
    needs: build
    permissions:
      id-token: write   # required so the workflow can auth to FlakeHub
      contents: read
    uses: DeterminateSystems/public-slice-mirror/.github/workflows/subset-mirror.yml@main
    with:
      flake-name: DeterminateSystems/nix-artifacts
      rolling: false
      tag: v3.21.1
